### ISSUE TITLE
Implement filtering by fandom

### ISSUE THREAD

**Issue by Tzarnal** [jsmnbom/ao3-enhancements#11]
I like the crossover filter and the tag filters area great idea but that only filters based on how many fandoms are included.

You can put a fandom tag in the tag filter but it won't actually look at the fandoms list. 

I'd like to be able to filter out given fandoms when browsing. It doesn't personally matter much if the existing filter also checks the fandom list or if there is a separate filter option for fandoms.

**Comment by jsmnbom** [comment]
I could've sworn it also filtered fandoms, but I guess not. Sorry for the late reply, and even more sorry that I don't really have time to work on this addon atm, but I'll keep it in mind for sure (and PRs are ofc welcome too ^^)

**Comment by jsmnbom** [comment]
This will be implemented in the upcoming version ^.^
