### ISSUE TITLE
Browsing with the plugin adds works that weren't visited to history

### ISSUE THREAD

**Issue by spacebees** [jsmnbom/ao3-enhancements#13]
Since I started using it some works that I haven't visited have been marked as visited in my full history. 

With the ao3 history being a bit delayed in updating I wasn't able to test it properly, but I'm sure that it happens at least when visiting an author's profile (all works displayed on the page will end up marked as having been visited once) and 90% that it might happen with other pages as well, while it doesn't seem to happen automatically on the page of a wrangled tag that can be filtered. 

I have a hunch that it's TrackWorks, but as mentioned I couldn't really test.

**Comment by cheride** [comment]
I'm having this same problem. Since I do use my history, I've removed the extension from my browser to hopefully prevent any further problems, but, unfortunately, the bogus entries did not miraculously disappear from the history.

**Comment by jsmnbom** [comment]
This is unfortunately a known problem. See here for more info: https://github.com/jsmnbom/ao3-enhancements/issues/6

**Comment by jsmnbom** [comment]
Next version will have track works removed entirely, and a hopefully better version implemented soon. That was the best fix I could do for now.
