### ISSUE TITLE
Logging into ao3 enhancements destroyed my ability to use AO3

### ISSUE THREAD

**Issue by sabhassy** [jsmnbom/ao3-enhancements#16]
Logged into the extension for the beta enhancements (see what I left kudos on, etc) and now whenever I visit any page on AO3 I am simply met with 'try again' in the top left corner. Same thing happened on my phone. Tried in incognito mode and it worked perfectly fine because I wasn't logged in. After removing the extension it went back to normal (took a few minutes though) but I really did like using the extension and would prefer to have it. Sad that it made AO3 completely functionless when I had it in my Chrome extensions.

**Comment by jsmnbom** [comment]
Yea, this is probably due to the "Track Works" feature. I'm hoping to either overhaul or remove it soon, it has been causing far too many issues.

**Comment by jsmnbom** [comment]
Next version will have track works removed entirely, and a hopefully better version implemented soon. That was the best fix I could do for now.

**Comment by sabhassy** [comment]
Thanks!
