### ISSUE TITLE
Issue with reading speeds over 400wpm

### ISSUE THREAD

**Issue by dandelion212** [jsmnbom/ao3-enhancements#17]
I can set my reading speed above 400wpm perfectly fine by typing my speed manually into the box, and it works as expected. However, if I re-open the settings for the extension, it resets to the slider's max of 400, so if I want to change any other settings, I have to change my speed again. This is super minor lol, more of an annoyance than anything. Love the work you do!!

**Comment by jsmnbom** [comment]
Will be fixed next release, thanks :D
