### ISSUE TITLE
Filter for Time Since Last Update

### ISSUE THREAD

**Issue by keoShine** [jsmnbom/ao3-enhancements#22]
Would creating a filter to hide unfinished works that haven't been updated in X amount of time in order to filter out likely abandoned works be a thing that's possible..?

**Comment by jsmnbom** [comment]
I'm a little hesitant to add features like that that can already be easily done with AO3's own filtering system. At least too many of them, as the options interface is going to get unruly really fast. I would consider maybe adding a way of adding some default features that will be applied whereever possible, but that definitely won't arrive for this release, sorry.
