### ISSUE TITLE
Hiding a tag in the should automatically remove any space at the beginning and end

### ISSUE THREAD

**Issue by robmart** [jsmnbom/ao3-enhancements#27]
Very annoying when pasting a tag from AO3 and it inserts a space at the beginning, since you have to delete the tag and redo it.

**Comment by jsmnbom** [comment]
i believe this is fixed in a future unreleased version, but I'll keep this issue open as a reminder, thanks ^^

**Comment by jsmnbom** [comment]
Released :)
