### ISSUE TITLE
Buttons to block/hide users with

### ISSUE THREAD

**Issue by BobTheSkrull** [jsmnbom/ao3-enhancements#29]
I'm not sure how difficult it is to add buttons for existing features, but something that would allow a user to click near a name and quickly add it to the "Exclude Works By" list would be really helpful. Something similar for tags would be nice too, but I'd imagine that would be a bit more complicated (limited space means you'd have to relegate it to the context menu, different sections for different types of tags, etc).

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
