### ISSUE TITLE
working on latest Firefox Android

### ISSUE THREAD

**Issue by tcooperma** [jsmnbom/ao3-enhancements#33]
Anyone know how to get this working on the latest Firefox /Android?

Does it work in Chrome/Android?

Does this work in Opera?

**Comment by 58straps** [comment]
I've gotten it working in Opera and Firefox, and I believe it also works on Chrome. This is only for desktop/PC versions though; I've been trying to find other ways to get it working on mobile (especially Firefox) and so far have had no luck.

**Comment by jsmnbom** [comment]
The latest firefox fennec should allow you to download and install the extension directly from addons.mozilla.org :D
