### ISSUE TITLE
Flag works with suspicious amounts of Kudos

### ISSUE THREAD

**Issue by SomeDumName** [jsmnbom/ao3-enhancements#35]
Some works on archive of our own have more kudos than they have hits
or have 441% kudos to (hits/chapters) but not nearly enough chapters to justify it (100 chapters is enough for people to leave kudos early yet fall off)
Please add a feature to signal to users that those works are suspicious.

**Comment by jsmnbom** [comment]
I will not be adding this, since it is often simply a case of AO3 caching the hit counts for longer.
