### ISSUE TITLE
filter all tags containing a phrase

### ISSUE THREAD

**Issue by ohheyitsyouagain** [jsmnbom/ao3-enhancements#36]
I tend to hc a lot of characters as aro, meaning that I tend to ignore any shippy fics with them. it would be nice to just filter all "/This Guy" fics instead of having to filter out every ship individually.

**Comment by tigrrlily** [comment]
This would be incredibly helpful

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
