### ISSUE TITLE
History is filled with unvisited works

### ISSUE THREAD

**Issue by gitgitbal** [jsmnbom/ao3-enhancements#38]
Works that I've have not visited are showing up in my history.
It looks like they are coming from user pages that I've accessed (user works, series or bookmarks)and from search results. It might be due to the way the tracking functions?
In any case, this is now filled with fics I haven't actually accessed and is not helping keeping my own real history clean.
Is there a way to remedy this?

Thanks!

**Comment by CrypticCherry** [comment]
Switch to one of the pre-release versions: https://github.com/jsmnbom/ao3-enhancements/releases

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
