### ISSUE TITLE
Higher wpm limit?

### ISSUE THREAD

**Issue by candycoatedrox** [jsmnbom/ao3-enhancements#39]
I'm a fast reader, and I took the wpm test linked on the settings page. It came out as 738, and I tried copying that into the settings, but when I reloaded the page to check it'd saved (because I didn't see a save button), it had reset to 400, the end of the slider. I was wondering if it'd be possible to increase the wpm limit? I know it's an edge case, but it'd still be nice.

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
