### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by Flyndragon** [jsmnbom/ao3-enhancements#4]
When on AO3, the site keeps flickering between the edited and unedited site, to the point where I had to uninstall the extension.

**Comment by Flyndragon** [comment]
figured it out, this only happened because I set my reading speed at over 400 wpm. I set it at the max the slide bar goes to, 400 wpm, and it doesn't happen anymore!

**Comment by jsmnbom** [comment]
I've noticed this too. It shouldn't have anything to do with setting your wpm too high. I think it was caused by the UserUpdater module not being able to determine if you're logged in or not. I've disabled the automatic user updating in version 0.3.2 which is out on firefox and pending on chrome. Please try it out (with your wpm > 400) and see if it still happens there :)

**Comment by Flyndragon** [comment]
Yeah, It just started happening again, frustrating, and then AO3 won't load at all. I think your right. How to I disable automatic user updating? I cannot find that option.

**Comment by jsmnbom** [comment]
There's unfortunately no option to do that, You need to update to version 0.3.2 on the extension, where I have forcibly disabled it. I'm guessing you're on chrome? Chrome web store is veeery slow at approving updates though, so it could take a day or so. If you can't wait and want to test it out now you can download the unsigned version 0.3.2 (from here https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.3.2 choose the one with chrome in its name), but it's kinda difficult to install (need to follow instructions here: https://stackoverflow.com/a/24577660/3920144 - basically unpack the zip, use developer mode and load the folder).

**Comment by Flyndragon** [comment]
That's alright! I'm on windows and not especially good with computers, so I'll wait for the update to roll out on the chrome store. Meanwhile, I have raised my wpm, and it doesn't seem to be a problem, and turning off all tracking features seems to have improved stability? Thank you for your help!!

**Comment by jsmnbom** [comment]
Turning off track works would indeed increase stability yea. In 0.3.2, I've made them work a bit slower but a lot more stable too.

Thanks for the report, please open it again or a new one if you find issues with 0.3.2 :D
