### ISSUE TITLE
Problem with reading list sync

### ISSUE THREAD

**Issue by gitgitbal** [jsmnbom/ao3-enhancements#46]
First issue is the creation of the collection that fails with message: "Could not create collection: undefined"
Then if I manually create a collection and set it be used, when trying to sync the first time, it give the following error: "Create bookmark did not redirect like we thought it would."
![error](https://user-images.githubusercontent.com/108962636/197379801-91aa3155-066b-4fe4-b724-6d5ca55ee731.png)

On subsequent tries, it says it is successful but 
- no bookmark is created
- the reading list is completely reset to 0
![list_reset](https://user-images.githubusercontent.com/108962636/197379811-0cba4950-1530-4b67-b896-c78b050134a1.png)

This is on MacOS Catalina and Monterey, chrome version 106.0.5249.119 

Is it a problem in the way I set up my collection? If so, how can I have the "create" button working for this?  Or is there an another issue?
Thanks

**Comment by jsmnbom** [comment]
"Fixed" in v0.5. (Reading List Feature is gone - sorry :/)
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
