### ISSUE TITLE
Request for new filters to hide works

### ISSUE THREAD

**Issue by Clem2605** [jsmnbom/ao3-enhancements#52]
Hello!

I love the extension, and it's already a big help, especially the "Hide works based on language" one. Since I read in two of the most represented languages in my preferred fandoms, it's quicker to hide the works in other languages than to filter by one language, then the other.

Since it's so helpful, I wanted to suggest the option to hide works based on fandom, exactly the same way.

When I search by tag, I get works from every other fandoms, and the AO3 interface isn't very good at filtering every work except those that belong to my fandoms, especially when they aren't well-known ones. I can try to filter the ones I don't want out, but the site gets overwhelmed after a certain number of requests.

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
