### ISSUE TITLE
Estimated reading time: higher wpm limit

### ISSUE THREAD

**Issue by shiningsun21** [jsmnbom/ao3-enhancements#63]
Hi, your AO3 Enhancements extension is wonderful! I was wondering if you could increase the wpm limit to a 1000? It's such a useful feature, but 400 is a bit low for some readers. 
I am so happy with this extension overall and appreciate the time and effort you've put into this.

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
