### ISSUE TITLE
[Request] Ability to block fandoms, since adding them to blocked tags didn't work

### ISSUE THREAD

**Issue by aaronhowser1** [jsmnbom/ao3-enhancements#65]
![Screenshot_20231217_180708_Firefox](https://github.com/jsmnbom/ao3-enhancements/assets/15698722/63ada517-51a5-45c6-ad00-7847f5f4ebcb)
![Screenshot_20231217_180705_Firefox](https://github.com/jsmnbom/ao3-enhancements/assets/15698722/2a89a7d3-4fde-4901-b010-086b4d5e53d4)

On android

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
