### ISSUE TITLE
[Request] wildcard for hide works with tags to use in relationships

### ISSUE THREAD

**Issue by EvergreenMoth8** [jsmnbom/ao3-enhancements#66]
Is it possible to implement a wildcard token to use in the Hide works, like say i don't want any relationships that involve character XYZ and i could put "*/XYZ" in the hide works based on tags section. im asking this because personally i dont care for reading works that involve a relationship with the reader and rather than having to add each /reader relationship i could use a wildcard and remove any reader relationship, 

i already have just  Reader, Reader-insert, and Self-inserts as a tag to hide works, but not everyone adds them and it would be rude to just go to a work asking them to add that tag because i personally dont want to see it or read it

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.

Hope substring and regex is enough for you?  :)
