### ISSUE TITLE
kodus

### ISSUE THREAD

**Issue by seybeans** [jsmnbom/ao3-enhancements#68]
not really an issue but it kodus here if you want to fix that, idk
![Screenshot (1)](https://github.com/jsmnbom/ao3-enhancements/assets/163688533/0db79d85-74f3-4d6c-b6f2-3546eddf8eeb)

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
