### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by Mieekaserra** [jsmnbom/ao3-enhancements#69]
## maintainer notice:
> [contrastellar](https://github.com/contrastellar) in https://github.com/jsmnbom/ao3-enhancements/issues/69#issuecomment-2083263005
> For anyone curious and is just skim reading this issue.
> The current dev build of this extension can be installed and seems* to run as expected.

See rest of [comment](https://github.com/jsmnbom/ao3-enhancements/issues/69#issuecomment-2083263005) for more info

---------------------------
Version: Release v0.4.0-beta.9
Browser: Firefox

3 hours ago it was working fine, but in the last hour the floating button and the menu bar has stopped loading, 

console is now showing the following error
[AO3E] TypeError: t is null
    ready moz-extension://d9bea787-5f5e-42a0-bf94-2c33aa2f8c2a/content_script/content_script.js:20
    Qt moz-extension://d9bea787-5f5e-42a0-bf94-2c33aa2f8c2a/content_script/content_script.js:20
[content_script.js:20:147795](moz-extension://d9bea787-5f5e-42a0-bf94-2c33aa2f8c2a/content_script/content_script.js)
    <anonymous> moz-extension://d9bea787-5f5e-42a0-bf94-2c33aa2f8c2a/content_script/content_script.js:20

Have tried a clean reinstall incase it was something in my settings.

**Comment by peony4584** [comment]
its not just you the same is happening for me (using crome)

**Comment by EvergreenMoth8** [comment]
same for me using Opera GX

**Comment by EvergreenMoth8** [comment]
looking into it this line "t = Array.from(e.querySelectorAll(":scope > li.dropdown")).pop()" is giving an error "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')"

**Comment by SleepyKitten-Games** [comment]
Also happening with Vivaldi (v. 6.6.3271.55) on Windows 11, extension version 0.3.2
This is the error I see in the console:
<img width="356" alt="A screenshot of the console, showing an error that reads [AO3E] TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at Tools_Tools.ready (chrome-extension://eljennickgdbghppcaenkcinjafmnfoi/content_script/content_script.js:6:39459)
    at run (chrome-extension://eljennickgdbghppcaenkcinjafmnfoi/content_script/content_script.js:6:52120)" src="https://github.com/jsmnbom/ao3-enhancements/assets/24967983/d645efde-cbe5-41be-9113-37572eb614e7">

**Comment by ffuentesm** [comment]
Same, stoped working a few hours ago.

**Comment by rosetips** [comment]
same thing here, using chrome.

**Comment by jsmnbom** [comment]
Yep, completely stopped working. Luckily I *am* back to working on it, but since chrome webstore will not let me upload a fixed version using a manifest V2, and I am nly currently about 50% done with the MV3 version, then you will unfortunately have to wait a bit for a fix. I'm really sorry.

**Comment by jsmnbom** [comment]
I've attempted to start a build (https://github.com/jsmnbom/ao3-enhancements/commit/14471ec4699e4ee7638082bcb65d276ff7ff1d5a) for the people comfortable installing beta versions directly from files.

(also for the people using beta versions: do note that the reading list feature is going away next full release - I lost interest in maintaining it, and it was buggy as hell - sorry)

**Comment by jsmnbom** [comment]
Okay for firefox (and similar) users, you can now use https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.4.0-beta.10 (just click the .xpi file).
Chrome users please see: https://github.com/jsmnbom/ao3-enhancements/wiki/Installing-prereleases or wait till the Manifest V3 version is ready.

Phew... this took a while to get working and it's 5am now - i'm going to bed. Hopefully nothing else blows up in the meantime :P

**Comment by Mieekaserra** [comment]
> I've attempted to start a build ([14471ec](https://github.com/jsmnbom/ao3-enhancements/commit/14471ec4699e4ee7638082bcb65d276ff7ff1d5a)) for the people comfortable installing beta versions directly from files.
> 
> (also for the people using beta versions: do note that the reading list feature is going away next full release - I lost interest in maintaining it, and it was buggy as hell - sorry)

Shame, the reading list feature for tracking what chapters i'd already read, and which fic's i'd started then dropped was one of the main features of the extention that i was intrested in using (even without the ability to sync it).

in the meantime however - the new beta works great.

**Comment by contrastellar** [comment]
For anyone curious and is just skim reading this issue. 

The current dev build of this extension can be installed and seems* to run as expected.

### If you have Firefox

The [current latest beta is working still](https://github.com/jsmnbom/ao3-enhancements/releases/download/v0.4.0-beta.10/ao3-enhancements-0.4.0-beta.10.firefox.xpi) on Firefox 125.0.3 (Working on an Nov 2023 Macbook Pro, Apple M3 Pro chip). Just download that file and run it.

### If you have chrome

follow [this guide](https://github.com/jsmnbom/ao3-enhancements/wiki/Installing-prereleases). It seems straight forward, but I don't use chrome so I have no idea if it works or doesn't work -- I'm not gonna mess with it, but please someone let me know, I'd love to know!

This thread hasn't been updated in ~1 month, but it seems that the dev build is stable enough to run short-term (probably medium term) if you so desire.

### About the failed build on main
It looks like (just from glancing through the logs while I'm at work) that the release push failed for some reason? Dunno why, considering the release went through?

### For jsmnbom -- 
Thank you for your work on this extension! I can't imagine it's easy with `10131` lines of code (according to `cloc`, not counting JSON/HTML).

**Comment by jsmnbom** [comment]
Yeah the release push failed, but I manually created the release from 1) local source archive 2) local chrome build 3) signed build from AMO. Should be identical to what the build system would have made but yeah, this was easier for a hotfix, and next version needs big changes to the pipeline so yee.

Thankuu <3 I'm actually almost done with a new release (so my timeline of a month turned out to be more or less corrrect. Im currently in a move but moving to have a prerelease out within  week or so, and then a full proper (chrome web store & AMO) release out a week after if all goes well (i'm in the middle of a move rn, so this is also assuming that goes well).

The dev build should be fairly stable BUT i has the in  progress feature of "Reading List" which never worked well and is flaky and therefore it's getting axed for next release - so i don't recommend using it at all cause you will just be disappointed when it's gone xD If there's enough demand maybe in the future i can work on integrating it back in a more robust way.

**Comment by SargeLovesFandoms** [comment]
> Yeah the release push failed, but I manually created the release from 1) local source archive 2) local chrome build 3) signed build from AMO. Should be identical to what the build system would have made but yeah, this was easier for a hotfix, and next version needs big changes to the pipeline so yee.
> 
> Thankuu <3 I'm actually almost done with a new release (so my timeline of a month turned out to be more or less corrrect. Im currently in a move but moving to have a prerelease out within week or so, and then a full proper (chrome web store & AMO) release out a week after if all goes well (i'm in the middle of a move rn, so this is also assuming that goes well).
> 
> The dev build should be fairly stable BUT i has the in progress feature of "Reading List" which never worked well and is flaky and therefore it's getting axed for next release - so i don't recommend using it at all cause you will just be disappointed when it's gone xD If there's enough demand maybe in the future i can work on integrating it back in a more robust way.

So glad it's being fixed, I can't wait to use the new one. I'm not very good at trying to do the hotfix. Thank you so much for your hard work, it's appreciated.

**Comment by SleepyKitten-Games** [comment]
While the .xpi works perfectly on desktop Firefox, even in Firefox Beta for Android I can't get the .xpi to work. So I'm hoping that eventually the extension itself will work so I can have AO3 Enhancements on both desktop and mobile, because this extension has been a lifesaver for me.

**Comment by jsmnbom** [comment]
Please help test v0.5.
Hoping to have a full release (also for chrome) out this week, but since it's such a big overhaul of more or less all the code, I'd like some feedback on if stuff works first ^^
Please make a backup of your settings before trying out this pre-release build!!! (this is done by pressing Export on the options page)

https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.0-beta.14
See [this guide](https://github.com/jsmnbom/ao3-enhancements/wiki/Installing-prereleases) on how to install.

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
