### ISSUE TITLE
Extension is Broken :(

### ISSUE THREAD

**Issue by juhmendez** [jsmnbom/ao3-enhancements#71]
The button for the AO3 Enhancements extension doesn't show up on the website anymore and for me everything under "Blurb Statistics" on the extension page has stopped working as well. The 'Show kudos/hits ratio', the 'Reading time' and 'Finish reading at' features are all broken. None of them actually show up on AO3 anymore.

**Comment by EvergreenMoth8** [comment]
> The button for the AO3 Enhancements extension doesn't show up on the website anymore and for me everything under "Blurb Statistics" on the extension page has stopped working as well. The 'Show kudos/hits ratio', the 'Reading time' and 'Finish reading at' features are all broken. None of them actually show up on AO3 anymore.

https://github.com/jsmnbom/ao3-enhancements/issues/69#issuecomment-2083263005

**Comment by jsmnbom** [comment]
Fixed in v0.5. 
See https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.4.
