### ISSUE TITLE
Works are not being blocked by tags

### ISSUE THREAD

**Issue by ChaoticAdventure** [jsmnbom/ao3-enhancements#75]
Firefox
The tags, in the options menu when you right click on Ao3, says they are hidden (has the little checkmark). However, the works themselves are not hidden.
Works are hidden by language and amount of fandoms just fine, but not with tags. Sorry to put up an issue so close to the update, but I noticed this feature suddenly stopped working.
Also I've never done this before, sorry if I did it wrong/this is not the right way to raise an issue.

**Comment by DrWhoFan13** [comment]
I figured out a workaround (editing the JSON), and updating to 0.5.4 _briefly_ fixed it before breaking it again.

**Comment by ChaoticAdventure** [comment]
(I am emailing in, hopefully this adds itself to the thread correctly)
I do use an AO3 skin, all it does is add colors to the tags. Like, it makes ship tags highlight green, etc. Changes background colors. It worked in tandem with the plugin before the update. I can’t do screenshots right this moment but in like 9 hours I can.
It is all tags, on all pages as far as I can tell. I will try to describe what’s happening, it’s a bit odd.

I right click and go to the little menu for a tag I want to block (let’s just say it’s “Self-Insert”). I click the box, “Hide Tag”. It shows the little checkmark. 

The work is NOT hidden even though it should be.

Then, I see what happens on a random gibberish tag, like “This is an established ship btw” (I would not have blocked this in the past). The check mark by the “hide tag” box is still checked, even though I did not try to block that tag at all. Throughout all of this, no works are being blocked.

Hopefully this helps diagnose the issue. Or maybe I’m misunderstanding how it works. :)

**Comment by DrWhoFan13** [comment]
For the sake of more information, I have the same issue as ChaoticAdventurer; but my site skin affects more than tag color, recoloring the entire site a la dark mode.

I also have some settings on AO3 changed from default, but nothing I assume would affect the extension outside of muting some users.

My site language is English as well.

**Comment by nlgraham** [comment]
Using Firefox 128.0.3. Also running into works not being hidden. Pretty much all tags seem to have "Hide" checked in the context menu, regardless of whether I had them hidden before or not, but no fics are being hidden on any page based on the tags. Language filtering is working. Refreshing the page does not change anything. 

I do not use any skins. My site language is set to English, and I have a few users muted and all my Display preferences are unchecked.

Maybe related, I also don't see a way to add tags in the extension options, nor do I see the list I used to have.

**Comment by DrWhoFan13** [comment]
I assume that there not being a way to add tags in settings is deliberate, given that I can't either; but I still have my settings from prior to this update.

**Comment by jsmnbom** [comment]
Okay I found an error in how options were saved that could explain a lot of this weirdness.

**Comment by jsmnbom** [comment]
Wait @DrWhoFan13 @nlgraham are you saying that your settings page looks different from this:
![image](https://github.com/user-attachments/assets/21db662d-bf05-4c73-b206-c90f6964c045)
?

**Comment by ChaoticAdventure** [comment]
It does not look like that for me!! There is no list. Nothing between the
slider and the notes/help.

**Comment by nlgraham** [comment]
![image](https://github.com/user-attachments/assets/56cb6c23-60d6-45ff-aa4a-73686f1bd4cd)
This is all I have for the Tags section

**Comment by jsmnbom** [comment]
oh... welp.. yea that's not good :P
would you be comfortable sharing an export of your settings? either privately or by simply drag+dropping the file in the comment text field on here?

**Comment by DrWhoFan13** [comment]
> Wait @DrWhoFan13 are you saying that your settings page looks different from this?

I have dark mode on, so I didn't see the plus button until I hovered over the area. Otherwise, it looks exactly the same aside from the tags blocked. (Also, mind changing that?)

**Comment by ChaoticAdventure** [comment]
Here are mine for further reference. I am seeing the same thing as that second screenshot, with just the line, no table.

￼

**Comment by nlgraham** [comment]
[AO3-Enhancements_options_2024-07-29_14-29-39.json](https://github.com/user-attachments/files/16414822/AO3-Enhancements_options_2024-07-29_14-29-39.json)
Here's the options only - I can send you the whole thing via email if you need that instead.

**Comment by jsmnbom** [comment]
Okay frick, i was afraid of that. Looks like your filters have been removed during the update somehow.
Which version did you two update from? Any of the 0.4 betas or from 0.3.2?

**Comment by ChaoticAdventure** [comment]
It did it automatically for me. I don’t think I was on any of the betas? I’ve never updated it manually, so if it wouldn’t go to them automatically I wouldn’t have used them.

**Comment by jsmnbom** [comment]
Danm.. yeah, i found the error now too. Options were different in 0.3.2 than i had thought and the migration i wrote broke it. Migration code is fixed now in new version. Currently trying to figure out how to fix it for the people like you that got an update that then broke stuff (tho your tag list is unfortunately gone unless you made an export backup before it updated - very sorry)

**Comment by jsmnbom** [comment]
Okay, version 0.5.5 should be out with a fix for firefox soonish (not sure how to manually trigger an update), and for chrome probably in about a day.

**Comment by jsmnbom** [comment]
https://github.com/jsmnbom/ao3-enhancements/releases/tag/v0.5.5

**Comment by jsmnbom** [comment]
Thanks a ton for your quick help @ChaoticAdventure :D

**Comment by DrWhoFan13** [comment]
Much appreciated.

**Comment by ChaoticAdventure** [comment]
Thank you so much for the quick fix!! Everything works now :)
