### ISSUE TITLE
Showing authors doesn't work

### ISSUE THREAD

**Issue by DrWhoFan13** [jsmnbom/ao3-enhancements#78]
For context, I'm using V0.5.5; Firefox v129 beta channel.

Recently (as in today), an author I follow has posted a work with tags I've blocked due to personal distaste; but when I toggled the "show author" feature on said author; it didn't do anything. Even when the option is checked, it still hides the work and the popup said that the author has been unshown; even if the author is _supposed_ to be shown. 

Manually adding it doesn't work either, as doing so in the settings doesn't change anything; nor does altering a JSON export.

**Comment by jsmnbom** [comment]
Ah yes... the hide/show for tags and hide/show for authors is seperate right now. So if the tag filter hides something, only a tag filter can show it..

Thinking about it, that's kinda really unintuitive tho.. thanks for the report :)

**Comment by DrWhoFan13** [comment]
> Thinking about it, that's kinda really unintuitive tho.. thanks for the report :)
Not a problem.

Oh, and before I forget, inputting in _any_ information about the author; whether username, user ID or pseud, doesn't work.
