### ISSUE TITLE
[Enhancement] Make this extension work on archiveofourown.gay?

### ISSUE THREAD

**Issue by Mary126** [jsmnbom/ao3-enhancements#88]
archiveofourown.org is blocked in my country, so sometimes it's a hassle to get to that website, but it's mirror archiveofourown.gay is fine. Is it possible to make it work on the mirror?

**Comment by jsmnbom** [comment]
Unfortunately that will disable the extension for everyone until they accept the extension running on the new domain which I would rather avoid. You could try updating your hosts file with something like 
`
archiveofourown.org 104.21.84.201
`
to make the .org point to the (current) ip of the .gay mirror.
